
-- NeighbourWise / Supabase Postgres schema


-- Enable PostGIS
create extension if not exists postgis;

-- Optional: keep everything in public
set search_path to public;


-- 1) locality_point
-- Used for suburb/locality search suggestions and map centering

create table if not exists public.locality_point (
    id integer generated by default as identity primary key,
    geom geometry(Point, 4326),
    "UFI" integer,
    "PFI" integer,
    "NAME_ID" integer,
    "PLACE_NAME" varchar,
    "PLACELABEL" varchar,
    "FTYPE_CODE" varchar,
    "FEATSUBTYP" varchar,
    "HIERARCHY" integer,
    "STATE" varchar,
    "SCALE_USEC" varchar,
    "PFI_CR" date,
    "UFI_CR" date
);

create index if not exists idx_locality_point_place_name
    on public.locality_point ("PLACE_NAME");

create index if not exists idx_locality_point_placelabel
    on public.locality_point ("PLACELABEL");

create index if not exists idx_locality_point_geom
    on public.locality_point
    using gist (geom);

-- 2) locality_polygon
-- Used for official suburb boundaries

create table if not exists public.locality_polygon (
    id integer generated by default as identity primary key,
    geom geometry(MultiPolygon, 4326),
    "UFI" integer,
    "PFI" varchar,
    "LOCALITY" varchar,
    "GAZLOC" varchar,
    "VICNAMESID" integer,
    "TASK_ID" integer,
    "PFI_CR" date,
    "UFI_OLD" integer,
    "UFI_CR" date,
    "LABEL_USE_" integer
);

create index if not exists idx_locality_polygon_locality
    on public.locality_polygon ("LOCALITY");

create index if not exists idx_locality_polygon_vicnamesid
    on public.locality_polygon ("VICNAMESID");

create index if not exists idx_locality_polygon_geom
    on public.locality_polygon
    using gist (geom);



-- 3) heat_features
-- Used for heat overlay / heat summaries

create table if not exists public.heat_features (
    ogc_fid integer generated by default as identity primary key,
    mb_code16 varchar,
    sa1_main16 varchar,
    sa2_name16 varchar,
    sa3_code16 varchar,
    sa3_name16 varchar,
    sa4_code16 varchar,
    sa4_name16 varchar,
    gcc_code16 varchar,
    sa2_main16 varchar,
    pershrbtre double precision,
    peranyveg double precision,
    pershrub double precision,
    pertr03_10 double precision,
    pertr10_15 double precision,
    pertr15pl double precision,
    uhi18_m double precision,
    pergrass double precision,
    lga varchar,
    peranytree double precision,
    geom geometry(MultiPolygon, 4326)
);

create index if not exists idx_heat_features_ogc_fid
    on public.heat_features (ogc_fid);

create index if not exists idx_heat_features_sa2_name16
    on public.heat_features (sa2_name16);

create index if not exists idx_heat_features_lga
    on public.heat_features (lga);

create index if not exists idx_heat_features_geom
    on public.heat_features
    using gist (geom);

-- 4) vegetation_features
-- Used for vegetation overlay / vegetation summaries

create table if not exists public.vegetation_features (
    fid integer generated by default as identity primary key,
    uniqueid integer,
    mb_reclass varchar,
    type integer,
    landtype varchar,
    areasqm double precision,
    areaanyveg double precision,
    peranyveg double precision,
    geom geometry(MultiPolygon, 4326)
);

create index if not exists idx_vegetation_features_fid
    on public.vegetation_features (fid);

create index if not exists idx_vegetation_features_uniqueid
    on public.vegetation_features (uniqueid);

create index if not exists idx_vegetation_features_type
    on public.vegetation_features (type);

create index if not exists idx_vegetation_features_geom
    on public.vegetation_features
    using gist (geom);



-- 5) zoning_features

create table if not exists public.zoning_features (
    id integer generated by default as identity primary key,
    geom geometry(MultiPolygon, 4326),
    fid bigint,
    schemecode varchar,
    lga_code varchar,
    lga varchar,
    zone_code varchar,
    zone_desc varchar
);

create index if not exists idx_zoning_features_zone_code
    on public.zoning_features (zone_code);

create index if not exists idx_zoning_features_zone_desc
    on public.zoning_features (zone_desc);

create index if not exists idx_zoning_features_lga
    on public.zoning_features (lga);

create index if not exists idx_zoning_features_geom
    on public.zoning_features
    using gist (geom);


-- 7) crime_suburb_summary
-- Latest-year suburb-level crime context summary used by safety scoring

create table if not exists public.crime_suburb_summary (
    id bigserial primary key,
    year integer,
    suburb_key text,
    postcode text,
    suburb_name text,
    lga_key text,
    lga_name text,
    total_offences integer,
    person_offences integer,
    property_offences integer,
    disorder_offences integer,
    other_offences integer,
    total_offence_percentile numeric(8,4),
    person_crime_percentile numeric(8,4),
    property_crime_percentile numeric(8,4),
    disorder_crime_percentile numeric(8,4),
    crime_context_score_raw numeric(8,4),
    crime_context_score numeric(5,2),
    crime_context_label text,
    crime_context_summary text
);

create index if not exists idx_crime_summary_suburb_key
    on public.crime_suburb_summary (suburb_key);

create index if not exists idx_crime_summary_suburb_name
    on public.crime_suburb_summary (suburb_name);

create index if not exists idx_crime_summary_postcode
    on public.crime_suburb_summary (postcode);

create index if not exists idx_crime_summary_lga_key
    on public.crime_suburb_summary (lga_key);

create index if not exists idx_crime_summary_year
    on public.crime_suburb_summary (year);


-- 8) pet_friendly_spaces
-- Polygon dog park / pet-friendly park areas

create table if not exists public.pet_friendly_spaces (
    pet_id bigint primary key,
    raw_id varchar,
    source_id varchar,
    access varchar,
    addr_housenumber varchar,
    addr_postcode varchar,
    addr_state varchar,
    addr_street varchar,
    addr_suburb varchar,
    area varchar,
    geom geometry(Polygon, 4326)
);

create index if not exists idx_pet_friendly_spaces_source_id
    on public.pet_friendly_spaces (source_id);

create index if not exists idx_pet_friendly_spaces_access
    on public.pet_friendly_spaces (access);

create index if not exists idx_pet_friendly_spaces_addr_suburb
    on public.pet_friendly_spaces (addr_suburb);

create index if not exists idx_pet_friendly_spaces_geom
    on public.pet_friendly_spaces
    using gist (geom);


-- 9) pet_friendly_spaces_points
-- Point dog park / pet-friendly park locations used for markers and nearest queries

create table if not exists public.pet_friendly_spaces_points (
    pet_point_id bigint primary key,
    raw_id varchar,
    source_id varchar,
    access varchar,
    addr_housenumber varchar,
    addr_postcode varchar,
    addr_state varchar,
    addr_street varchar,
    addr_suburb varchar,
    geom geometry(Point, 4326)
);

create index if not exists idx_pet_friendly_spaces_points_source_id
    on public.pet_friendly_spaces_points (source_id);

create index if not exists idx_pet_friendly_spaces_points_access
    on public.pet_friendly_spaces_points (access);

create index if not exists idx_pet_friendly_spaces_points_addr_suburb
    on public.pet_friendly_spaces_points (addr_suburb);

create index if not exists idx_pet_friendly_spaces_points_geom
    on public.pet_friendly_spaces_points
    using gist (geom);


-- 10) Raw OSM backup tables
-- These preserve the original imported OSM columns before normalisation.

create table if not exists public.pet_friendly_spaces_raw_backup (
    id varchar primary key,
    geom geometry(Geometry, 4326),
    "@id" varchar,
    access varchar,
    "addr:housenumber" varchar,
    "addr:postcode" varchar,
    "addr:state" varchar,
    "addr:street" varchar,
    "addr:suburb" varchar,
    area varchar,
    barrier varchar,
    check_date date,
    description varchar,
    dog varchar,
    fence varchar,
    fence_type varchar,
    fixme varchar,
    height varchar,
    landuse varchar,
    leisure varchar,
    lit varchar,
    mobile varchar,
    name varchar,
    natural varchar,
    note varchar,
    opening_hours varchar,
    operator varchar,
    "operator:type" varchar,
    source varchar,
    surface varchar,
    type varchar,
    website varchar,
    wheelchair varchar
);

create table if not exists public.pet_friendly_spaces_points_raw_backup (
    id varchar primary key,
    geom geometry(Geometry, 4326),
    "@id" varchar,
    access varchar,
    "addr:housenumber" varchar,
    "addr:postcode" varchar,
    "addr:state" varchar,
    "addr:street" varchar,
    "addr:suburb" varchar,
    area varchar,
    barrier varchar,
    check_date date,
    description varchar,
    dog varchar,
    fence varchar,
    fence_type varchar,
    fixme varchar,
    height varchar,
    landuse varchar,
    leisure varchar,
    lit varchar,
    name varchar,
    natural varchar,
    note varchar,
    opening_hours varchar,
    operator varchar,
    "operator:type" varchar,
    source varchar,
    surface varchar,
    type varchar,
    website varchar,
    wheelchair varchar,
    "@geometry" varchar
);


-- 11) Safety / comfort OSM scoring tables
-- Used by safety score activity, noise, and transport comfort calculations

create table if not exists public.osm_activity_scoring (
    id integer generated by default as identity primary key,
    osm_id varchar,
    name varchar,
    category varchar,
    source_tag varchar,
    activity_weight double precision,
    amenity varchar,
    shop varchar,
    tourism varchar,
    leisure varchar,
    opening_hours varchar,
    geom geometry(Geometry, 4326)
);

create index if not exists idx_osm_activity_scoring_geom
    on public.osm_activity_scoring
    using gist (geom);

create index if not exists idx_osm_activity_scoring_category
    on public.osm_activity_scoring (category);

create table if not exists public.osm_noise_scoring (
    id integer generated by default as identity primary key,
    osm_id varchar,
    name varchar,
    feature_type varchar,
    source_tag varchar,
    noise_weight double precision,
    lit varchar,
    maxspeed_num integer,
    lanes_num integer,
    surface varchar,
    geom geometry(Geometry, 4326)
);

create index if not exists idx_osm_noise_scoring_geom
    on public.osm_noise_scoring
    using gist (geom);

create index if not exists idx_osm_noise_scoring_feature_type
    on public.osm_noise_scoring (feature_type);

create table if not exists public.osm_transport_comfort_scoring (
    id integer generated by default as identity primary key,
    osm_id varchar,
    name varchar,
    mode varchar,
    public_transport varchar,
    stop_comfort_weight double precision,
    lit varchar,
    shelter varchar,
    bench varchar,
    covered varchar,
    wheelchair varchar,
    tactile_paving varchar,
    geom geometry(Geometry, 4326)
);

create index if not exists idx_osm_transport_comfort_scoring_geom
    on public.osm_transport_comfort_scoring
    using gist (geom);

create index if not exists idx_osm_transport_comfort_scoring_mode
    on public.osm_transport_comfort_scoring (mode);


-- 12) Council links and postcode/locality lookup

create table if not exists public.council_links (
    id bigserial primary key,
    coverage_type text not null default '31_metro_council',
    lga_name text not null unique,
    council_name text not null,
    home_url text not null,
    projects_or_works_url text,
    planning_url text,
    strategies_or_plans_url text,
    vicplan_property_report_url text,
    victorian_planning_schemes_url text,
    planning_scheme_amendments_dataset_url text,
    last_checked date,
    notes text,
    created_at timestamp with time zone not null default now(),
    updated_at timestamp with time zone not null default now()
);

create table if not exists public.postcode_locality_lookup (
    id bigserial primary key,
    postcode text not null,
    locality text not null,
    state text not null,
    type text,
    status text,
    lat double precision not null,
    lng double precision not null,
    sa1_code_2021 text,
    sa1_name_2021 text,
    sa2_code_2021 text,
    sa2_name_2021 text,
    lga_name text,
    lga_code text,
    geom geometry(Point, 4326)
);

create index if not exists idx_postcode_locality_lookup_postcode
    on public.postcode_locality_lookup (postcode);

create index if not exists idx_postcode_locality_lookup_locality
    on public.postcode_locality_lookup (locality);

create index if not exists idx_postcode_locality_lookup_geom
    on public.postcode_locality_lookup
    using gist (geom);


-- 13) Census profile tables
-- Processed 2021 Census profiles at SAL, SA2, and POA geography levels

create table if not exists public.census_sal_profile (
    sal_code_2021 text primary key,
    total_population integer,
    median_age numeric(6,2),
    median_household_income_weekly numeric(12,2),
    median_personal_income_weekly numeric(12,2),
    median_family_income_weekly numeric(12,2),
    median_rent_weekly numeric(12,2),
    median_mortgage_monthly numeric(12,2),
    average_household_size numeric(6,2),
    age_0_14_count integer,
    age_15_24_count integer,
    age_25_34_count integer,
    age_65_plus_count integer,
    age_0_14_pct numeric(8,4),
    age_15_24_pct numeric(8,4),
    age_25_34_pct numeric(8,4),
    age_65_plus_pct numeric(8,4),
    born_overseas_count integer,
    language_other_than_english_count integer,
    born_overseas_pct numeric(8,4),
    language_other_than_english_pct numeric(8,4),
    need_for_assistance_count integer,
    need_for_assistance_pct numeric(8,4),
    couple_family_with_children_count integer,
    one_parent_family_count integer,
    other_family_count integer,
    total_families integer,
    couple_family_with_children_pct numeric(8,4),
    one_parent_family_pct numeric(8,4),
    family_households_count integer,
    non_family_households_count integer,
    total_households integer,
    family_households_pct numeric(8,4),
    non_family_households_pct numeric(8,4),
    lone_person_households_count integer,
    group_households_count integer,
    lone_person_households_pct numeric(8,4),
    group_households_pct numeric(8,4),
    no_car_households_count integer,
    one_car_households_count integer,
    two_car_households_count integer,
    three_plus_car_households_count integer,
    car_households_total integer,
    no_car_households_pct numeric(8,4),
    two_plus_car_households_pct numeric(8,4),
    owned_outright_count integer,
    owned_with_mortgage_count integer,
    rented_count integer,
    tenure_total integer,
    owned_outright_pct numeric(8,4),
    owned_with_mortgage_pct numeric(8,4),
    renters_pct numeric(8,4),
    owner_occupied_pct numeric(8,4),
    train_to_work_count integer,
    bus_to_work_count integer,
    tram_to_work_count integer,
    car_driver_to_work_count integer,
    walk_to_work_count integer,
    worked_from_home_count integer,
    travel_to_work_total integer,
    public_transport_to_work_pct numeric(8,4),
    car_to_work_pct numeric(8,4),
    walk_to_work_pct numeric(8,4),
    worked_from_home_pct numeric(8,4),
    rent_to_income_ratio numeric(8,4),
    created_at timestamp with time zone default now()
);

create table if not exists public.census_sa2_profile (
    sa2_code_2021 text primary key,
    total_population integer,
    median_age numeric(6,2),
    median_household_income_weekly numeric(12,2),
    median_personal_income_weekly numeric(12,2),
    median_family_income_weekly numeric(12,2),
    median_rent_weekly numeric(12,2),
    median_mortgage_monthly numeric(12,2),
    average_household_size numeric(6,2),
    age_0_14_count integer,
    age_15_24_count integer,
    age_25_34_count integer,
    age_65_plus_count integer,
    age_0_14_pct numeric(8,4),
    age_15_24_pct numeric(8,4),
    age_25_34_pct numeric(8,4),
    age_65_plus_pct numeric(8,4),
    born_overseas_count integer,
    language_other_than_english_count integer,
    born_overseas_pct numeric(8,4),
    language_other_than_english_pct numeric(8,4),
    need_for_assistance_count integer,
    need_for_assistance_pct numeric(8,4),
    couple_family_with_children_count integer,
    one_parent_family_count integer,
    other_family_count integer,
    total_families integer,
    couple_family_with_children_pct numeric(8,4),
    one_parent_family_pct numeric(8,4),
    family_households_count integer,
    non_family_households_count integer,
    total_households integer,
    family_households_pct numeric(8,4),
    non_family_households_pct numeric(8,4),
    lone_person_households_count integer,
    group_households_count integer,
    lone_person_households_pct numeric(8,4),
    group_households_pct numeric(8,4),
    no_car_households_count integer,
    one_car_households_count integer,
    two_car_households_count integer,
    three_plus_car_households_count integer,
    car_households_total integer,
    no_car_households_pct numeric(8,4),
    two_plus_car_households_pct numeric(8,4),
    owned_outright_count integer,
    owned_with_mortgage_count integer,
    rented_count integer,
    tenure_total integer,
    owned_outright_pct numeric(8,4),
    owned_with_mortgage_pct numeric(8,4),
    renters_pct numeric(8,4),
    owner_occupied_pct numeric(8,4),
    train_to_work_count integer,
    bus_to_work_count integer,
    tram_to_work_count integer,
    car_driver_to_work_count integer,
    walk_to_work_count integer,
    worked_from_home_count integer,
    travel_to_work_total integer,
    public_transport_to_work_pct numeric(8,4),
    car_to_work_pct numeric(8,4),
    walk_to_work_pct numeric(8,4),
    worked_from_home_pct numeric(8,4),
    rent_to_income_ratio numeric(8,4),
    created_at timestamp with time zone default now()
);

create table if not exists public.census_poa_profile (
    poa_code_2021 text primary key,
    total_population integer,
    median_age numeric(6,2),
    median_household_income_weekly numeric(12,2),
    median_personal_income_weekly numeric(12,2),
    median_family_income_weekly numeric(12,2),
    median_rent_weekly numeric(12,2),
    median_mortgage_monthly numeric(12,2),
    average_household_size numeric(6,2),
    age_0_14_count integer,
    age_15_24_count integer,
    age_25_34_count integer,
    age_65_plus_count integer,
    age_0_14_pct numeric(8,4),
    age_15_24_pct numeric(8,4),
    age_25_34_pct numeric(8,4),
    age_65_plus_pct numeric(8,4),
    born_overseas_count integer,
    language_other_than_english_count integer,
    born_overseas_pct numeric(8,4),
    language_other_than_english_pct numeric(8,4),
    need_for_assistance_count integer,
    need_for_assistance_pct numeric(8,4),
    couple_family_with_children_count integer,
    one_parent_family_count integer,
    other_family_count integer,
    total_families integer,
    couple_family_with_children_pct numeric(8,4),
    one_parent_family_pct numeric(8,4),
    family_households_count integer,
    non_family_households_count integer,
    total_households integer,
    family_households_pct numeric(8,4),
    non_family_households_pct numeric(8,4),
    lone_person_households_count integer,
    group_households_count integer,
    lone_person_households_pct numeric(8,4),
    group_households_pct numeric(8,4),
    no_car_households_count integer,
    one_car_households_count integer,
    two_car_households_count integer,
    three_plus_car_households_count integer,
    car_households_total integer,
    no_car_households_pct numeric(8,4),
    two_plus_car_households_pct numeric(8,4),
    owned_outright_count integer,
    owned_with_mortgage_count integer,
    rented_count integer,
    tenure_total integer,
    owned_outright_pct numeric(8,4),
    owned_with_mortgage_pct numeric(8,4),
    renters_pct numeric(8,4),
    owner_occupied_pct numeric(8,4),
    train_to_work_count integer,
    bus_to_work_count integer,
    tram_to_work_count integer,
    car_driver_to_work_count integer,
    walk_to_work_count integer,
    worked_from_home_count integer,
    travel_to_work_total integer,
    public_transport_to_work_pct numeric(8,4),
    car_to_work_pct numeric(8,4),
    walk_to_work_pct numeric(8,4),
    worked_from_home_pct numeric(8,4),
    rent_to_income_ratio numeric(8,4),
    created_at timestamp with time zone default now()
);

create or replace view public.census_sa2_profile_valid as
select *
from public.census_sa2_profile
where total_population is not null
  and total_population > 0;

create or replace view public.census_sal_profile_valid as
select *
from public.census_sal_profile
where total_population is not null
  and total_population > 0;

create or replace view public.census_poa_profile_valid as
select *
from public.census_poa_profile
where total_population is not null
  and total_population > 0;


-- 11) Census lookup and crosswalk tables
-- Used to map searched suburbs/postcodes onto SA2 profile rows

create table if not exists public.sal_lookup (
    sal_code_2021 text primary key,
    sal_name_2021 text not null,
    created_at timestamp with time zone default now()
);

create index if not exists idx_sal_lookup_name
    on public.sal_lookup (sal_name_2021);

create table if not exists public.sa2_lookup (
    sa2_code_2021 text primary key,
    sa2_name_2021 text not null,
    created_at timestamp with time zone default now()
);

create index if not exists idx_sa2_lookup_name
    on public.sa2_lookup (sa2_name_2021);

create table if not exists public.poa_lookup (
    poa_code_2021 text primary key,
    postcode text not null,
    display_label text,
    created_at timestamp with time zone default now()
);

create index if not exists idx_poa_lookup_postcode
    on public.poa_lookup (postcode);

create table if not exists public.sal_to_sa2 (
    id bigserial primary key,
    sal_code_2021 text not null
        references public.census_sal_profile(sal_code_2021),
    sal_name_2021 text,
    sa2_code_2021 text not null
        references public.census_sa2_profile(sa2_code_2021),
    sa2_name_2021 text,
    overlap_area_pct numeric(8,4),
    confidence text,
    created_at timestamp with time zone default now()
);

create index if not exists idx_sal_to_sa2_sal_name
    on public.sal_to_sa2 (sal_name_2021);

create index if not exists idx_sal_to_sa2_sa2_code
    on public.sal_to_sa2 (sa2_code_2021);

create index if not exists idx_sal_to_sa2_sa2_name
    on public.sal_to_sa2 (sa2_name_2021);

create table if not exists public.poa_to_sa2 (
    id bigserial primary key,
    poa_code_2021 text not null
        references public.census_poa_profile(poa_code_2021),
    postcode text,
    sa2_code_2021 text not null
        references public.census_sa2_profile(sa2_code_2021),
    sa2_name_2021 text,
    overlap_area_pct numeric(8,4),
    confidence text,
    created_at timestamp with time zone default now()
);

create index if not exists idx_poa_to_sa2_postcode
    on public.poa_to_sa2 (postcode);

create index if not exists idx_poa_to_sa2_sa2_code
    on public.poa_to_sa2 (sa2_code_2021);

create index if not exists idx_poa_to_sa2_sa2_name
    on public.poa_to_sa2 (sa2_name_2021);


-- 12) Reproducible suburb score runs
-- Batch-generated recommendation scores. Keep runs immutable so score changes
-- caused by refreshed crime, AQI, POI, or spatial data can be compared later.

create table if not exists public.score_runs (
    id bigserial primary key,
    scoring_version text not null,
    persona text not null default 'default',
    time_minutes integer not null default 20,
    delay_ms integer not null default 0,
    status text not null default 'running'
        check (status in ('running', 'completed', 'completed_with_errors', 'failed')),
    source_metadata jsonb not null default '{}'::jsonb,
    started_at timestamp with time zone not null default now(),
    completed_at timestamp with time zone,
    error_message text
);

create index if not exists idx_score_runs_started_at
    on public.score_runs (started_at desc);

create index if not exists idx_score_runs_version_persona_time
    on public.score_runs (scoring_version, persona, time_minutes);

create index if not exists idx_score_runs_status_persona_started
    on public.score_runs (status, persona, started_at desc);

create table if not exists public.suburb_scores (
    id bigserial primary key,
    score_run_id bigint not null
        references public.score_runs(id)
        on delete cascade,
    locality_point_id bigint,
    suburb_name text not null,
    suburb_label text,
    postcode text,
    latitude double precision not null,
    longitude double precision not null,
    accessibility_score integer,
    safety_score integer,
    environment_score integer,
    liveability_score integer,
    status text not null default 'completed'
        check (status in ('completed', 'failed')),
    error_message text,
    breakdown jsonb not null default '{}'::jsonb,
    calculated_at timestamp with time zone not null default now(),
    unique (score_run_id, suburb_name, postcode)
);

create index if not exists idx_suburb_scores_run
    on public.suburb_scores (score_run_id);

create index if not exists idx_suburb_scores_suburb_name
    on public.suburb_scores (suburb_name);

create index if not exists idx_suburb_scores_liveability
    on public.suburb_scores (liveability_score desc);

create or replace view public.latest_suburb_scores as
select distinct on (ss.suburb_name, ss.postcode, sr.persona, sr.time_minutes)
    ss.*,
    sr.persona,
    sr.scoring_version,
    sr.time_minutes,
    sr.started_at as score_run_started_at
from public.suburb_scores ss
join public.score_runs sr
    on sr.id = ss.score_run_id
where sr.status in ('completed', 'completed_with_errors')
  and ss.status = 'completed'
order by
    ss.suburb_name,
    ss.postcode,
    sr.persona,
    sr.time_minutes,
    sr.started_at desc,
    ss.calculated_at desc;



-- Quick check view for geometry types
create or replace view public.spatial_table_summary as
select
    f_table_schema as schema_name,
    f_table_name   as table_name,
    f_geometry_column as geometry_column,
    type,
    srid
from public.geometry_columns;

